config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  post "/menu_items/cart" => "menu_items#cart"
  get "/menu_items/cart_items" => "menu_items#cart_items", as: :menu_items_cart_items
  resources :menu_items
  resources :orders
  resources :order_items
  resources :menus
  resources :users

  post "/orders/invoices" => "orders#invoices"
  post "/orders/customer_invoices" => "orders#customer_invoices", as: :customer_invoices
  get "/admin/report" => "admin#reports", as: :reports
  get "/admin/invoice_bills" => "admin#invoice_bills", as: :invoice_bills
  get "/myorders" => "menu_items#myorders", as: :my_orders
  get "/admin" => "admin#index", as: :admin_page
  get "/clerk" => "admin#clerk", as: :clerk_page
  post "/admin" => "users#adding_user", as: :users_add_user
  get "/admin/add_user" => "users#adding_user_page", as: :users_add_user_page
  get "/admin/users_info" => "users#info", as: :users_info
  post "/menus/:id/update" => "menus#updation"
  post "/menu_items/:id/update" => "menu_items#updation"
  post "/orders/display" => "orders#display"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/views/admin/clerk.html.erb
<main class="MainPage">

  <div class="Clerk-home">
    <%= submit_tag "View Pending Orders",class: "Pending-orders",onclick:"location.href='/orders'"%>
    <%= submit_tag "Add New Order", class: "Clerk-order",onclick:"location.href='/menu_items'"%>
  </div>

</main>

app/views/admin/error.html.erb
<section class="Access-error">
  <h1 class="Error-title"> You don't have access rights </h1>
  <img class="Error-image" src="/Access.jpg">
  <h1 class="Error-message"> Try contacting praveen or pooji for admin rights </h1>
</section>

app/views/admin/index.html.erb
<style>
body{
  background-image: url('res11.jpg');
  background-repeat:no-repeat;
  background-attachment: fixed;
  background-size: cover
}
</style>

<body>
  <main class="MainPage">
    <div class="split left">
      <div class="centered">
        <img src="/admin.png" class="centered img">
      </div>
    </div>

    <div class="split right">
      <div class="top">
        <p class="Admin-option">
          <%= link_to "Edit menu", menus_path%>
        </p>

        <p class="Admin-option">
          <%= link_to "View pending orders", orders_path %>
        </p>

        <p class="Admin-option">
          <%= link_to "All the users", users_info_path %>
        </p>

        <p class="Admin-option">
          <%= link_to "Add Users", users_add_user_page_path %>
        </p>

        <p class="Admin-option">
          <%= link_to "Place orders", menu_items_path%>
        </p>

        <p class="Admin-option">
          <%= link_to "View Reports", invoice_bills_path%>
        </p>

      </div>
    </div>
  </main>
</body>

app/views/admin/report.html.erb
<main class="ReportPage">
  <%= form_with(url: "/orders/invoices", method: "POST") do %>
    <ul class="Invoice-item">
      <h1>FROM: <%= date_field_tag 'from_date',nil, class: "From-date" %> </h1>
      <h1>TO: <%= date_field_tag 'to_date',nil, class: "To-date" %> </h1>
      <h1> <%= submit_tag "View all Reports", class: "Invoice-allOrder"%> </h1>
    </ul>
   <% end %>

  <%= form_with(url: "/orders/customer_invoices", method: "POST") do %>
    <ul class="Invoice-item">
      <h1> FROM: <%= date_field_tag 'from_date',nil, class: "From-date" %> </h1>
      <h1> TO: <%= date_field_tag 'to_date',nil, class: "To-date" %> </h1>
    </ul>
    <ul class="Invoice-item">
      <h1 class="Customer-id"> CustomerID: <%= number_field_tag "customer_id",nil, placeholder:"customer-id", class: "ID-input"%> </h1>
      <h1> <%= submit_tag "View customer Report", class: "Invoice-order"%> </h1>
    </ul>
  <% end %>

  <% if @orders %>
    <% if @orders!=[] %>
      <h1 class="Invoice-title"> All Invoice bills </h1>
      <label class="Hint">[HINT: Hover over the bills to view details] </label>
      <ul class="Invoice-items">
        <li class="Invoice-item">
          <h2 align="center" class="Order-idHead"> Order-id </h2>
          <h2 align="left" class="OrderedUser-nameHead"> User-Name </h2>
          <h2 align="center" class="OrderItems-head"> Items </h2>
          <h2 align="right" class="Order-valueHead"> Total Bill </h2>
        </li>
        <% @orders.each do |order|%>
          <% if User.exists?(id = order["user_id"])%>
            <li class="Invoice-item" >
              <h2 align="center" class="Order-id"> <%= order["id"]%> </h2>
              <h2 align="left" class="OrderedUser-name"> <%= User.find(order["user_id"]).first_name %> <%= User.find(order["user_id"]).last_name %> </h2>
              <h2 align="center" class="OrderItems"> <%= Order.find(order["id"]).order_items.count%> </h2>
              <h2 align="right" class="Order-value"> <%= order["value"] %> </h2>
              <h2 align="left"><%= image_submit_tag  "/info.png",class: "Invoice-info",onclick: "location.href='/orders/#{order["id"]}'" %></h2>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <h1 class="NoBills-message"> Sorry! No bills available in selected date </h1>
    <% end %>
  <%end %>
</main>

app/views/admin/rerport.html.erb
<main class="ReportPage">
  <li>
    <input class="From-date" type="date" name="from_date">
    <input class="To-date" type="date" name="to_date">
  </li>
  <li>
    <%= form_with(url: "/orders/invoices", method: "POST",class: "AddOrder") do %>
      <%= submit_tag "View all Reports", class: "MenuItems-cart"%>
    <% end %>
  </li>
  <li>
    <%= form_with(url: "", method: "",class: "AddOrder") do %>
      <%= number_field_tag "custumer_id", placeholder:" customer id " %>
      <%= submit_tag "View customer Report", class: "MenuItems-cart",onclick:"location.href=''"%>
    <% end %>
  </li>

</main>