config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  post "/menu_items/cart" => "menu_items#cart"
  get "/menu_items/cart_items" => "menu_items#cart_items", as: :menu_items_cart_items
  resources :menu_items
  resources :orders
  resources :order_items
  resources :menus
  resources :users

  post "/orders/invoices" => "orders#invoices"
  post "/orders/customer_invoices" => "orders#customer_invoices", as: :customer_invoices
  get "/admin/report" => "admin#reports", as: :reports
  get "/admin/invoice_bills" => "admin#invoice_bills", as: :invoice_bills
  get "/myorders" => "menu_items#myorders", as: :my_orders
  get "/admin" => "admin#index", as: :admin_page
  get "/clerk" => "admin#clerk", as: :clerk_page
  post "/admin" => "users#adding_user", as: :users_add_user
  get "/admin/add_user" => "users#adding_user_page", as: :users_add_user_page
  get "/admin/users_info" => "users#info", as: :users_info
  post "/menus/:id/update" => "menus#updation"
  post "/menu_items/:id/update" => "menu_items#updation"
  post "/orders/display" => "orders#display"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true
  #validates :password, presence: true
  validates :first_name, presence: true
  has_secure_password
  has_many :orders

  def self.get_customers
    User.all.where(role: "customer")
  end

  def self.get_clerks
    User.all.where(role: "clerk")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
    render "new"
  end

  def create
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      role: "customer",
      password: params[:password],
    )
    if new_user.save
      session[:current_user_id] = new_user.id
      flash[:notice] = "You've signed-up successfully!"
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  def info
    if current_user.role == "owner"
      @users_customer = User.get_customers
      @users_clerk = User.get_clerks
      render "users/users_info"
    else
      render "/admin/error"
    end
  end

  def adding_user_page
    if current_user.role == "owner"
      render "users/add_user"
    else
      render "/admin/error"
    end
  end

  def adding_user
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      role: params[:role],
      password: params[:password],
    )
    new_user.save!
    redirect_to admin_page_path
  end

  def destroy
    user = User.find(params[:id])
    @not_delivered_orders = Order.not_delivered_user(user.id)
    if @not_delivered_orders.length() != 0
      flash[:notice] = "Deliver the pending orders to delete user"
    else
      user.destroy
    end
    redirect_to users_info_path
  end
end

app/views/users/add_clerk.html.erb
<p class="NewUsers-title"> Add a new clerk! </p>

<section class="UsersNew">
  <%= form_with url: users_add_clerk_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label"> First name: </p>
      <%= form.text_field :first_name, class: "Form-input", autofocus: true %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label"> Last name: </p>
      <%= form.text_field :last_name , class: "Form-input"%>
      </div>
    <div class="Form-section">
      <p class="FormInput-label"> email: </p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>

    <div class="Form-section">
      <p class="FormInput-label"> password: </p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <%= form.submit "create", class: "Form-submit"%>
    </div>
  <% end %>

</section>

app/views/users/add_user.html.erb
<p class="NewUsers-title"> Add a new User! </p>

<section class="UsersNew">
  <%= form_with url: users_add_user_path do |form| %>
    <div class="Form-section">
      <p class="FormInput-label"> First name: </p>
      <%= form.text_field :first_name, class: "Form-input", autofocus: true %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label"> Last name: </p>
      <%= form.text_field :last_name , class: "Form-input"%>
      </div>
    <div class="Form-section">
      <p class="FormInput-label"> email: </p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>

    <div class="Form-section">
      <p class="FormInput-label"> password: </p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
    <p class="FormInput-label"> role: </p>
    <%= select_tag "role",
        options_for_select(["customer","clerk","owner"],"customer"),
        class: "Form-input"
      %>
    </div>
    <div class="Form-section">
      <%= form.submit "createUser", class: "Form-submit"%>
    </div>
  <% end %>

</section>

app/views/users/new.html.erb
<body>
<p class="NewUsers-title"> Welcome new user! </p>
<section class="UsersNew" style="background-image: url('signin.jpg');">
  <%= form_with url: users_path do |form| %>
    <div class="Form-section" >
      <p class="FormInput-label"> First name: </p>
      <%= form.text_field :first_name, class: "Form-input", autofocus: true %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label"> Last name: </p>
      <%= form.text_field :last_name , class: "Form-input"%>
      </div>
    <div class="Form-section">
      <p class="FormInput-label"> email: </p>
      <%= form.email_field :email, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <p class="FormInput-label"> password: </p>
      <%= form.password_field :password, class: "Form-input" %>
    </div>
    <div class="Form-section">
      <%= form.submit "Sign-up!", class: "Form-submit"%>
    </div>
  <% end %>
  <h3 class="Home-authenticate">
  Already have an account,
  <%= link_to "sign-in here", new_sessions_path%>
</h3>

</section>
</body>

app/views/users/users_info.html.erb
<main class="UserPage">
  <h1 class="User-info-title"> Available Users </h1>
  <section class="User-info-section">
    <ul>
      <h1 class="User-title"> Customers </h1>
      <% @users_customer.each do |user| %>
        <li class="User-item">
          <p class="User-id">
            Id:
          </p>
          <p class= "User-email">
            <%=user.id%>
          </p>
          <p class="User-bold">
            Name:
          </p>
          <p class= "User-name">
            <%= user.first_name%> <%= user.last_name%>
          </p>
          <p class="User-bold">
            Email:
          </p>
          <p class= "User-email">
            <%=user.email%>
          </p>


          <%= form_with(url: "/users/#{user.id}", method: "DELETE") do %>
            <%= image_submit_tag "/trashcan.svg", class: "UserItem-delete" %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <ul>
      <h1 class="User-title"> Clerks </h1>
        <% @users_clerk .each do |user| %>
          <li class="User-item">
            <p class="User-id">
              Id:
            </p>
            <p class= "User-email">
              <%=user.id%>
            </p>
            <p class="User-bold">
              Name:
            </p>
            <p class= "User-name">
             <%= user.first_name%> <%= user.last_name%>
            </p>
            <p class="User-bold">
              Email:
            </p>
            <p class= "User-email">
              <%=user.email%>
            </p>

            <%= form_with(url: "/users/#{user.id}", method: "DELETE") do %>
              <%= image_submit_tag "/trashcan.svg", class: "UserItem-delete" %>
            <% end %>
          </li>
        <% end %>
    </ul>
  </section>
</main>