config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  post "/menu_items/cart" => "menu_items#cart"
  get "/menu_items/cart_items" => "menu_items#cart_items", as: :menu_items_cart_items
  resources :menu_items
  resources :orders
  resources :order_items
  resources :menus
  resources :users

  post "/orders/invoices" => "orders#invoices"
  post "/orders/customer_invoices" => "orders#customer_invoices", as: :customer_invoices
  get "/admin/report" => "admin#reports", as: :reports
  get "/admin/invoice_bills" => "admin#invoice_bills", as: :invoice_bills
  get "/myorders" => "menu_items#myorders", as: :my_orders
  get "/admin" => "admin#index", as: :admin_page
  get "/clerk" => "admin#clerk", as: :clerk_page
  post "/admin" => "users#adding_user", as: :users_add_user
  get "/admin/add_user" => "users#adding_user_page", as: :users_add_user_page
  get "/admin/users_info" => "users#info", as: :users_info
  post "/menus/:id/update" => "menus#updation"
  post "/menu_items/:id/update" => "menu_items#updation"
  post "/orders/display" => "orders#display"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      if @current_user.role == "customer"
        redirect_to menu_items_path
      elsif @current_user.role == "owner"
        redirect_to admin_page_path
      else
        redirect_to clerk_page_path
      end
    else
      render "index"
    end
  end
end

app/views/home/index.html.erb
<style>
body{
  background-image: url('signup.jpg');
  background-repeat:no-repeat;
  background-attachment: fixed;
  background-size: cover
}
</style>
<body>
<h1 class="Home-title"> Welcome to Cafeteria management </h1>
<h3 class="Home-authenticate">
  New to the Cafeteria Management,
  <%= link_to "sign-up here", new_user_path%>
</h3>

<h3 class="Home-authenticate">
  Already have an account,
  <%= link_to "sign-in here", new_sessions_path%>
</h3>
</body>