config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  post "/menu_items/cart" => "menu_items#cart"
  get "/menu_items/cart_items" => "menu_items#cart_items", as: :menu_items_cart_items
  resources :menu_items
  resources :orders
  resources :order_items
  resources :menus
  resources :users

  post "/orders/invoices" => "orders#invoices"
  post "/orders/customer_invoices" => "orders#customer_invoices", as: :customer_invoices
  get "/admin/report" => "admin#reports", as: :reports
  get "/admin/invoice_bills" => "admin#invoice_bills", as: :invoice_bills
  get "/myorders" => "menu_items#myorders", as: :my_orders
  get "/admin" => "admin#index", as: :admin_page
  get "/clerk" => "admin#clerk", as: :clerk_page
  post "/admin" => "users#adding_user", as: :users_add_user
  get "/admin/add_user" => "users#adding_user_page", as: :users_add_user_page
  get "/admin/users_info" => "users#info", as: :users_info
  post "/menus/:id/update" => "menus#updation"
  post "/menu_items/:id/update" => "menu_items#updation"
  post "/orders/display" => "orders#display"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>  CafeteriaManagement  </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
body {
  background-image: url(<%= image_path 'background/main.jpg' %>);
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-size: cover
}
</style>
  <body class="Menu-body">
    <% if @current_user %>
      <div class="UserHeader">
        <p class=User-name>
          Welcome <%=@current_user.first_name%>
        </p>
        <div class="User-header">
          <% if @role=="customer" %>
            <%= link_to "My orders", my_orders_path, method:"get" %>
          <% end %>
          <p class="Sign-out">
            <%= link_to "Sign-out", destroy_session_path, method:"delete" %>
          </p>
        </div>
      </div>
    <% end %>

    <% if flash[:error] %>
      <p class="Flash-error">
        <%= flash[:error]%>
      </p>
    <% end %>

    <% if flash[:notice] %>
      <p class="Flash-notice">
        <%= flash[:notice] %>
      </p>
    <% end %>
    <%= yield %>
  </body>
</html>